language: go
go:
- master
install:
- go mod download
notifications:
  email: false
  slack:
    secure: T5gEt2VsZkzdS4PtkqOnpbd3AsyGDmN1b5UkABK8iM9eaR6PMlzPNSHbKv/GIg4gkGom3wWDgLCHp2TxkYDPnDWqODzOtmEbFJ4cakXDsMYoEf1IPc6NLiIHS6NSbPaxS5Www+wYCbram1m3ljXCMuiIA+g9VlWk78Kc15qTlDBvIhok04uEa3xMWDfjHfyvPdoRxPJYEpGn+Cns/5jjF9hAfA7eCkzWAEFGCrz1ZcTuoNO/rt149COOawH2ct86ntqu/JTXFhLCPcHjwWQAfV6ppzJlQpfwDedQgi8vBNgvu7JMOsgA6wyvFVJRqTwHpfNk09wWXjO8Z6JESMfEIwC+fC4+atoY0TFreVBYhO1WE2ZLo5g8wZc3wqvDIZ4m60cFNGlilRiuQHccdsbuKsR6D42avW//5uPbclsnkVXCv0aMU2lDkMrqLHsIS1cFuvTQ/h2ysxafUdycIYb1tqXny/NPVJDIAH+KTCtG88Ud7Jpqf0eXso/fMEc9tGX96MAxSj5N1Ez6qaiFre0+dAoLvUqGZw9xupriRG4k5qt6iUQM1WBxJ6VgSnq4ZmvkGajMtrarbgEgd7f9Xm0hbDnpZ9Kt9UNkN42bk5SrjwAkeGsRZGAI0niuALcGToCwHVHtuD5QHjZniIs2SFeWqqh0CdovhVo2wlY9jdagvXM=
os:
- linux
addons:
    code_climate:
        repo_token: ef2946f6d7f158a3103cc2ce5432ba4851ffd727d9613373c5d09859c85af9a4
